language: node_js
sudo: false

env:
  global:
    - MONGODB=2.6.12
    - MONGODB=3.0.14
    - MONGODB=3.2.12
    - MONGODB=3.4.3
    - MONGODB=3.5.5

  matrix:
    - SENECA_VER=@1.x.x
    - SENECA_VER=@2.x.x
    - SENECA_VER=@3.x.x

node_js:
  - "8"
  - "6"
  - "4"

matrix:
  fast_finish: true

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - pip install Pillow
  - python setup.py install

before_script:
  - npm uninstall seneca
  - npm install seneca$SENECA_VER
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

after_script:
  - pkill mongod
  - npm run cov

cache:
  directories:
      - node_modules



